#!/bin/sh

set -e

if [ "$(id -u)" != "0" ]; then
    exec sudo "${0}" "${@}"
fi

usage() {
    (
        echo "Usage: ${0} [prompt]"
    ) >&2
    exit 1
}

if [ "${1}" = "-h" ] || [ "${1}" = "--help" ] || [ "${1}" = "help" ]; then
    usage
fi

set -x

plymouthd
trap 'plymouth quit' EXIT

plymouth --show-splash
if [ "${1}" = "prompt" ]; then
    plymouth ask-for-password --prompt="Enter a password"
    plymouth ask-question --command=cat --prompt="Say a few words"
fi
plymouth display-message \
    --text="Sample status or error text for display to the user"

for i in $(seq 0 99); do
    # Zero-pad numbers less than 10
    if [ ${i} -lt 10 ]; then
        padded_i="0${i}"
    else
        padded_i="${i}"
    fi
    plymouth --update="Reticulating splines ${padded_i} with some very long text to see the end of the line disappearing in the theme because we set a gradient on the middle..."
    sleep 0.05
done
